@startuml ONCLeap

!include style/activity.plantuml
' By by Preston Lee, Daniel Mendoza

title ONCLeap Activity Diagram\nRendered %date('yyyy.MM.dd')


(*) --> ["New Request Started"] "New Hook Recieved"
note right: Note.
--> [Figure out corret context] "Correct syntax"
note right: "Actor and Patient ID are required and additional\n information can be included.\n Must follow FHIR CDS Format
--> === BStart ===

=== BStart === --> "Validate Actor ID"
note left: The actor ID is found through FHIR API
--> "Validate Patient ID"
note left: The Patient ID is found through FHIR API
--> "Identify Consent Form"
note left: Find the consent resource for this patient
if "Has Consent?" then
    --> "Consent Permit"
    --> ==BEnd==
else 
    -->"Respond No consent"
    if "More context" then
        --> "Redact Information"
        note right: Some or all the information will be taken out.
    endif
endif
--> === BEnd ===
--> "Post response"
--> (*)
@enduml



backend frontend typescript online form tutorial