@startuml ONCLeap Redact

!include style/activity.plantuml
' By by Preston Lee, Daniel Mendoza

title ONCLeap Redact Activity Diagram\nRendered %date('yyyy.MM.dd')


(*) --> ["New Request Started"] "New Hook Recieved"
--> [Context provided] "Correct syntax"
if "Valid" then
    --> [yes]"Validate Actor ID"
    if "Valid" then
        -->  [yes] "Validate Patient ID"
        if "Valid" then
            --> [yes]"Identify Consent Form"
            --> "Redact Data"
            --> ===BEnd===
        else
            --> [no]"Error Message"
        endif
    else
        --> [no]"Error Message"
    endif
else
    --> [no]"Error Message"
    --> ===BEnd===
endif
===BEnd=== --> [Send message]"Post response"
-->(*)
@enduml
