@startuml ONCLeap Check

!include style/activity.plantuml
' By by Preston Lee, Daniel Mendoza

title ONCLeap Check Activity Diagram\nRendered %date('yyyy.MM.dd')


(*) --> ["New Request Started"] "New Hook Recieved"
--> [Context provided] "Correct syntax"
if "Valid" then
    --> [yes]"Validate Actor ID"
    if "Valid" then
        -->  [yes] "Validate Patient ID"
        if "Valid" then
            --> [yes]"Identify Consent Form"
            if "Has Consent?" then
                --> [yes]"Respond Consent Permit"
                --> ==BEnd===
            else
                -->[no]"Respond No Consent"
                --> ===BEnd===
            endif
        else
            --> [no]"Respond Error Message"
        endif
    else
        --> [no]"Respond Error Message"
    endif
else
    --> [no]"Respond Error Message"
    --> ===BEnd===
endif
===BEnd=== --> [Send message]"Post response"
-->(*)
@enduml
