@startuml

!include style/activity.plantuml
' Example by Preston Lee

title Example Activity Diagram\nRendered %date('yyyy.MM.dd')


(*) --> [Create Diagram File] "New diagram assigned"
note right: Create one from scratch, or use a template.
--> [Author Content] "edit"
note right: This is just another note
--> === BStart ===

=== BStart === --> "Get Work Done"
if "It's late?" then
    --> [yes] "Go To Sleep"
    --> === BEnd ===

else
    -> [no] "Keep Working"
    --> === BEnd ===
endif

--> "Commit and Push File"
--> "Wait for Deployment" 
--> (*)

@enduml
