@startuml Sequence UML

title Sequence UML for SHARES Engine
participant Patient
participant Provider
database "FHIR server" as FHIR
participant "SHARES Engine\n(Consent Decision Service)" as SHARES
database SQL

== Patient Flow ==
Patient -> Patient: Login
Patient -> Patient: Add provider and organization to profile
Patient -> Patient: Fill out form to create Consent Document
Patient -> Patient: Add Consent Document to profile
Patient -> FHIR: Send Consent Document
FHIR -> SQL: Store Consent Document

== Provider Flow ==
Provider -> Provider: Login
Provider -> Provider: Input patient information into form
Provider -> SHARES: Send FHIR CDS hook
SHARES -> FHIR: Verify Consent through FHIR API
FHIR -> SQL: Find Consent Resource
alt Consent Found
    SQL -> FHIR: Return Consent
    FHIR -> SHARES: Send Consent
    SHARES -> FHIR: Get Patient Data
    FHIR -> SQL: Retrive Patient's Data
    SQL -> FHIR: Return Patient's Data
    FHIR -> SHARES: Send Patient's Data
    SHARES -> SHARES: Redact patient information based on consent
    SHARES -> Provider: Send redacted patient data
else No Consent Found
    SQL -> FHIR: Could Not Find Consent
    FHIR -> SHARES: No Consent
    SHARES -> Provider: Return Error "No consent found"
end
@enduml

