@startuml Patient Use Case Diagram
title Patient Use Case Diagram\nRendered %date('yyyy.MM.dd')
:Patient: as p1
:FHIR Server: as FHIR
left to right direction
rectangle OnlinePatientPortal{
    p1 --> (Login/Logout)
    p1 --> (Add Providers)
    p1 --> (Create Consents)
    p1 --> (Provide Consents)
    (Provide Consents) <-- FHIR
    p1 --> (Revoke Consents)
    (Revoke Consents) <-- FHIR
    p1 --> (Preview Shared Inforamtion)
    p1 --> (Upload Documents)
    p1 --> (View Health Inforamtion)
}

@enduml
